version: '3.8'

services:
  test_database:
    image: postgres:15
    container_name: todolist_test_db
    env_file: [".env"]
    ports: ["${TEST_DB_PORT}:5432"]
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    networks:
      - app-network
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    external: true