services:
  database:
    image: postgres:15
    container_name: todolist_db
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    profiles: ["dev"]
    networks:
      - app-network

  test_database:
    image: postgres:15
    container_name: todolist_test_db
    env_file: [".env"]
    ports: ["${TEST_DB_PORT}:5432"]
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    networks:
      - app-network
    profiles: ["test"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: todolist_backend
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app # Monta proyecto entero solo para DEV, para PROD solo montar /app
      - /var/run/docker.sock:/var/run/docker.sock
    profiles: ["dev", "test"]
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: todolist_prometheus
    ports: ["9090:9090"]
    volumes: ["./config/prometheus:/etc/prometheus"]
    command: --config.file=/etc/prometheus/prometheus.yml
    profiles: ["obs"]
    networks:
      - app-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: todolist_grafana
    ports: ["3000:3000"]
    volumes: ["./config/grafana/provisioning:/etc/grafana/provisioning"]
    profiles: ["obs"]
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: todolist_loki
    ports: ["3100:3100"]
    volumes: ["./config/loki:/etc/loki"]
    command: -config.file=/etc/loki/loki-config.yml
    profiles: ["obs"]
    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: todolist_promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    profiles: ["obs"]
    networks:
      - app-network
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: todolist_jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    profiles: ["obs"]
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: todolist_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - database
    profiles: ["dev"]

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin_data: