version: '3.8'

services:
  test_database:
    image: postgres:15
    container_name: todolist_test_db
    env_file: [".env"]
    ports: ["${TEST_DB_PORT}:5432"]
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    networks:
      - app-network

networks:
  app-network:
    external: true