services:
  database:
    image: postgres:15
    container_name: todolist_db
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    profiles: ["dev"]
    networks:
      - app-network

  backend:
    build: .
    container_name: todolist_backend
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app # Monta proyecto entero solo para DEV, para PROD solo montar /app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge