version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: todolist_prometheus
    ports: ["9090:9090"]
    volumes: ["./config/prometheus:/etc/prometheus"]
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: todolist_grafana
    ports: ["3000:3000"]
    volumes: ["./config/grafana/provisioning:/etc/grafana/provisioning"]
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: todolist_loki
    ports: ["3100:3100"]
    volumes: ["./config/loki:/etc/loki"]
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: todolist_promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - app-network
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: todolist_jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - app-network

networks:
  app-network:
    external: true