services:
  database:
    image: postgres:15
    container_name: todolist_db
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: todolist_backend
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - database
    volumes:
      - ./app:/app

  prometheus:
    image: prom/prometheus:latest
    container_name: todolist_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana-oss:latest
    container_name: todolist_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  promtail:
    image: grafana/promtail:latest
    container_name: todolist_promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: todolist_jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "4317:4317"        # Puerto para OTLP/gRPC
      - "4318:4318"        # Puerto para OTLP/HTTP
    environment: # <-- AÑADE ESTA SECCIÓN
      - COLLECTOR_OTLP_ENABLED=true