services:
  database:
    image: postgres:15
    container_name: todolist_db
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: todolist_backend
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - database
    volumes:
      - ./app:/app