from enum import Enum

class ErrorCode(str, Enum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USERS_NOT_FOUND = "USERS_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    PARAMS_NOT_FOUND = "PARAMS_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"